basePath: /
definitions:
  models.GetTransactionResp:
    properties:
      amount:
        type: string
      from:
        type: string
      to:
        type: string
    type: object
  models.GetWalletResp:
    properties:
      balance:
        type: string
    type: object
info:
  contact: {}
  title: Auth Service API
paths:
  /api/transaction/{hash}:
    get:
      description: Get USDT transaction details
      parameters:
      - description: Transaction Hash
        example: '<br>ERC20 USDT: "0xec1d31abdcb80d24d0d823b35f93ed30c837d26364928e3b1b97b3c1cdd7fe69",
          <br>TRC20 USDT: "d6d1cc1ab403bc0febfb69d7be0bd8bd2fc03e2a03c4e2bdfd74560bd66109be"'
        in: path
        name: hash
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetTransactionResp'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      tags:
      - transaction
  /api/wallet/{address}:
    get:
      description: Get USDT balance
      parameters:
      - description: Wallet Address
        example: '<br>ERC20 USDT: "0xe983fD1798689eee00c0Fb77e79B8f372DF41060", <br>TRC20
          USDT: "TLSrrT5DiF5TkWPffJVQNwKE7SrctRCcpD"'
        in: path
        name: address
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetWalletResp'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      tags:
      - wallet
swagger: "2.0"
