services:
  crypto-service:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      - CRYPTOSERVICE_CACHE_HOST=redis
      - CRYPTOSERVICE_CACHE_PORT=6379
      - CRYPTOSERVICE_CACHE_PASSWORD=
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

