logger:
  level: DEBUG
  filename: "./logs/app.log"
  max_size: 10
  max_backups: 5
  max_age: 30
  compress: true

transport:
  http:
    host: 0.0.0.0
    port: 8080

storages:
  cache:
    db_index: 0
    wallet_balance_ttl: 60
